### ISSUE TITLE
broken link to dataset

### ISSUE THREAD

**Issue by ocresearchking** [clovaai/cord#1]
Hello, I got a 404 message when trying to access the CORD link from the "Download Link" section of https://github.com/clovaai/cord/.

This is URL is linked to: https://github.com/clovaai/cord/blob/master

Thank you in advanced for addressing this.

**Comment by eleventh83** [comment]
Sorry for the late release. The link doesn't work yet. 
Initial data (1,000 sample) will be released within this year.

**Comment by eleventh83** [comment]
The sample data set is now released. You can download it by link. :-)

**Comment by wgharbieh** [comment]
Hi, there are only 400 images in the training set but 800 json files. Any plans to release the rest of the sample images? What about the full dataset?

**Comment by eleventh83** [comment]
> Hi, there are 401 images in the training set but 800 json files. Any plans to release the rest of the sample images? What about the full dataset?

Thank you for your report. I uploaded the whole image for training. Now you can access the entire 800 images.
