### ISSUE TITLE
full data request

### ISSUE THREAD

**Issue by Xiariyouhu** [clovaai/cord#2]
Hi! When could you offer the full 11000 datasets?

**Comment by eleventh83** [comment]
Additional data releases are expected mid this year (due to the removal of sensitive information).

**Comment by RamanHacks** [comment]
Any updates on this? Thanks in advance!

**Comment by mohammedayub44** [comment]
Same here. It would be great to have full dataset.

**Comment by nabsabraham** [comment]
any updates on this?

**Comment by him1411** [comment]
It has been than an year and the complete dataset has still not been released. Can you please share the link for the complete dataset.

**Comment by upmanager** [comment]
@him1411  Can you help me how can I use datasets on my Node project?
I need to scan France receipts. So many types of document are there.
