### ISSUE TITLE
Annotation tool availability

### ISSUE THREAD

**Issue by fatemerhmi** [clovaai/cord#5]
Hello, 

I was wondering if the annotation tool mentioned in the [paper](https://openreview.net/pdf?id=SJl3z659UH) is publicly available or not. 

Thanks

**Comment by VictorAtPL** [comment]
Hi @fatemerhmi ,

probably not.

For my personal project, I have setup my own annotation of receipts using Label Studio. This url might help:

https://labelstud.io/templates/optical_character_recognition.html

Best,
Piotr

**Comment by fatemerhmi** [comment]
Thanks @VictorAtPL .

**Comment by matg41** [comment]
hi @VictorAtPL 
Is it possible for you to share your pipeline?
Thanks
