### ISSUE TITLE
How do you guys match line items to its price?

### ISSUE THREAD

**Issue by renjithsasidharan** [clovaai/cord#6]
Once you are done with NER, how to you guys match its line item and its corresponding price?
A simple y coordinate matching will work in most cases, but there are cases where a line item is in two lines or the line item and its price are not in same line.

**Comment by eleventh83** [comment]
Sorry for the late reply. You can use `group_id` for that purpose. The corresponding `menu.name` and `menu.price` have the same `group_id`.
